### ISSUE TITLE
New Help Command Draft

### ISSUE THREAD

**Issue by Josefmathes** [general-ronimus/vwars#25]
const helpResponse = '```Welcome to Vibranium Wars!\
  \nObjective:\
  \nAcquire more vibranium bars than your competitors.\
  \n\
  \nHow to play:\
  \nUse /vw mine command to mine for vibranium ore and rare chances of equipment chests.\
  \n\
  \nUse /vw build and /vw train to build up your city or train up your military. A strong city better protects your ore from attackers. A strong military allows you to steal more ore from defenders.\
  \n\
  \nUse /vw attack to attack and steal a portion of a player’s ore. Dominate the conflict to rout your enemies.\
/nRouting a player allows for chances to steal extra ore/equipment and have a chance to dissolve a bar
  \n\
  \nUse /vw smelt to convert ore to vibranium bars. 1 bar costs 10,000 ore and cannot be stolen via attack command.\
  \n\
  \nEquipment chests unlock advanced commands. These can be purchased with ore using /vw buy, or found during mining.\
  \n\Fuel - gain 20 energy, 30 minute cool down. 100 max energy limit still applies\
  \n\Cloak - hide your stats and non-offensive moves from other players\
  \n\Jam - prevent opponent from attacking for 30 minutes\
  \n\Shield – Max 600%. Absorb incoming damage, shield deactivates once integrity reaches 0% or upon your next offensive move \
  \n\Sabotage - destroy 30% of an opponent\'s city\
  \n\Strike - destroy 30% of an opponent\'s military\
  \n\Nuke - destroy 40% of an opponent\'s city & military\
  \n\
  \nUse /vw leaderboard to check this war\'s standings and /vw stats for individual player information.\
  \nEnergy refresh rate is 1 per every 5 minutes.\
  \n\
  \n\End game: \
  \n\At the conclusion of the war, ore, cities and militaries are also converted (at the same rate as smelting) and added to your total vibranium bar count. Those with the most vibranium bars win the war.\
  \n\Use /vw hall to view the historical leaderboard for this server\'s Vibranium Wars players (COMING SOON).\
  \n\
  \nCreator and developer:\
  \nGeneral Ronimus\
  \n\
  \nGame design:\
  \nPlayBoyPK\
  \n```\

**Comment by Josefmathes** [comment]
well shoot. it took out all the tabs

**Comment by Josefmathes** [comment]
const helpResponse = '```Welcome to Vibranium Wars!\
   \nObjective:\
  \nAcquire more vibranium bars than your competitors.\
  \n\
  \nHow to play:\
  \nUse /vw mine command to mine for vibranium ore and rare chances of equipment chests.\
  \n\
  \nUse /vw build and /vw train to build up your city or train up your military. A strong city better protects your ore from attackers. A strong military allows you to steal more ore from defenders.\
  \n\
  \nUse /vw attack to attack and steal a portion of a player’s ore. Dominate the conflict to rout your enemies.\
/nRouting a player allows for chances to steal extra ore/equipment and have a chance to dissolve a bar
  \n\
  \nUse /vw smelt to convert ore to vibranium bars. 1 bar costs 10,000 ore and cannot be stolen via attack command.\
  \n\
  \nEquipment chests unlock advanced commands. These can be purchased with ore using /vw buy, or found during mining.\
  \n\Fuel - gain 20 energy, 30 minute cool down. 100 max energy limit still applies\
  \n\Cloak - hide your stats and non-offensive moves from other players\
  \n\Jam - prevent opponent from attacking for 30 minutes\
  \n\Shield – Max 600%. Absorb incoming damage, shield deactivates once integrity reaches 0% or upon your next offensive move \
  \n\Sabotage - destroy 30% of an opponent\'s city\
  \n\Strike - destroy 30% of an opponent\'s military\
  \n\Nuke - destroy 40% of an opponent\'s city & military\
  \n\
  \nUse /vw leaderboard to check this war\'s standings and /vw stats for individual player information.\
  \nEnergy refresh rate is 1 per every 5 minutes.\
  \n\
  \n\End game: \
  \n\At the conclusion of the war, ore, cities and militaries are also converted (at the same rate as smelting) and added to your total vibranium bar count. Those with the most vibranium bars win the war.\
  \n\Use /vw hall to view the historical leaderboard for this server\'s Vibranium Wars players (COMING SOON).\
  \n\
  \nCreator and developer:\
  \nGeneral Ronimus\
  \n\
  \nGame design:\
  \nPlayBoyPK\
  \n```\

**Comment by general-ronimus** [comment]
Changes were included in v2.1 beta pre-release
