### ISSUE TITLE
War conclusion behavior

### ISSUE THREAD

**Issue by general-ronimus** [general-ronimus/vwars#6]
As per official /help game description, at a war's conclusion ore, cities and militaries are converted to bars at smelting rate. Players with the most bars win. Currently we've planned out having 1st, 2nd and 3rd place with bonus bars percentage at each (playboypk suggests 20%, 10%, 5%). Some outstanding questions to answer:

- Should winners be determined pre-ore/city/military conversion?  Or post?
- We need to finalize the bars bonus, probably based on the first war's behavior. 
- Should the top 3 get some other sort of bonus besides medals and bars?  Perhaps their choice of equipment leading into the next war?

**Comment by PlayBoyPK** [comment]
For an additional bonus for top 3, we can give a set amount of vibranium to spend on equipment between wars that carries to the following one. 
So for 1st we can give 12000 ore to spend. They can do any combination from a nuke and fuel, to 4 cloaks or whatever they feel would help most.

**Comment by general-ronimus** [comment]
Ahh leaving the shop open during peace times, I like that idea. And the best part, it builds on top of pre-existing functionality 😄

**Comment by general-ronimus** [comment]
First version of this completed, will open a new ticket to move conclusion logic to the task master as an after commit transaction
